name: nav_stemi
description: EMS Navigation App for critical scenarios
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.4.2+1
  duration: ^3.0.13
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.2
  go_router: ^13.2.3
  google_navigation_flutter: ^0.4.0
  google_routes_flutter: ^1.0.0+1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  random_name_generator: ^1.3.0
  recase: ^4.1.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  time: ^2.1.4
  timeago_flutter: ^3.7.0
  units_converter: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logos/