name: nav_stemi
description: EMS Navigation App for critical scenarios
version: 0.0.20+20
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.2
  collection: ^1.18.0
  crypto: ^3.0.3
  csv: ^6.0.0
  dio: ^5.4.2+1
  duration: ^3.0.13 
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  fhir_r4: ^0.4.1
  fhir_r4_at_rest: ^0.4.0
  file_picker: ^8.3.1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  go_router: ^13.2.3
  google_navigation_flutter: ^0.4.0
  google_routes_flutter: ^1.0.0+1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  intl: ^0.19.0
  jose: ^0.3.4
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  mobile_scanner: ^6.0.2
  package_info_plus: ^8.3.0
  permission_handler: ^11.3.1
  random_name_generator: ^1.3.0
  recase: ^4.1.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  time: ^2.1.4
  timeago_flutter: ^3.7.0
  units_converter: ^3.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logos/