name: nav_stemi
description: EMS Navigation App for critical scenarios
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  envied: ^0.5.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  google_maps_flutter: ^2.5.1
  hooks_riverpod: ^2.4.9
  intl: ^0.18.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/