name: nav_stemi
description: EMS Navigation App for critical scenarios
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  intl: ^0.18.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
